### ISSUE TITLE
Issue in evaluation using pretrained weights

### ISSUE THREAD

**Issue by brojokm** [unilight/R-NET-in-Tensorflow#7]
I was trying to run evaluate.py as using the pretrained weights provided here http://slam.iis.sinica.edu.tw/demo/RNet/release.zip
But I'm getting  errors, and I have no clue why. Posting the whole output here.

python evaluate.py --model_path Models/save/rnet_model27.ckpt
Model Configs:
{'a_length': 20,
 'batch_size': 60,
 'char_emb': False,
 'char_emb_mat_dim': 8,
 'char_max_length': 37,
 'char_vocab_size': 1368,
 'emb_dim': 300,
 'glove': '300',
 'in_keep_prob': 1.0,
 'p_length': 300,
 'q_length': 30,
 'share_context_LSTM': True,
 'span_length': 20,
 'state_size': 75,
 'word_emb_dim': 300}
Reading data
Loaded 10570 examples from dev
/home/brojo/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Question and Passage Encoding
Tensor("encoding/stack:0", shape=(60, 30, 150), dtype=float32)
Tensor("encoding/stack_1:0", shape=(60, 300, 150), dtype=float32)
Question-Passage Matching
v_P Tensor("stack:0", shape=(60, 300, 75), dtype=float32)
Self-Matching Attention
h_P Tensor("Self_match/stack:0", shape=(60, 300, 150), dtype=float32)
Output Layer
r_Q Tensor("Sum_600:0", shape=(60, 150), dtype=float32)
h_t1a Tensor("Sum_600:0", shape=(60, 150), dtype=float32)
Tensor("strided_slice_1200:0", shape=(60, 150), dtype=float32)
h_t1a Tensor("strided_slice_1200:0", shape=(60, 150), dtype=float32)
[<tf.Tensor 'Softmax_601:0' shape=(60, 300) dtype=float32>, <tf.Tensor 'Softmax_602:0' shape=(60, 300) dtype=float32>]
Model built
W_uQ:0 (150, 75)
W_uP:0 (150, 75)
W_vP:0 (75, 75)
W_g_QP:0 (300, 300)
W_smP1:0 (75, 75)
W_smP2:0 (75, 75)
W_g_SM:0 (150, 150)
W_ruQ:0 (150, 150)
W_vQ:0 (75, 150)
W_VrQ:0 (30, 75)
W_hP:0 (150, 75)
W_ha:0 (150, 75)
B_v_QP:0 (75,)
B_v_SM:0 (75,)
B_v_rQ:0 (150,)
B_v_ap:0 (75,)
encoding/context_encoding/cell_0/fw/basic_lstm_cell/weights:0 (375, 300)
encoding/context_encoding/cell_0/fw/basic_lstm_cell/biases:0 (300,)
encoding/context_encoding/cell_0/bw/basic_lstm_cell/weights:0 (375, 300)
encoding/context_encoding/cell_0/bw/basic_lstm_cell/biases:0 (300,)
encoding/context_encoding/cell_1/fw/basic_lstm_cell/weights:0 (225, 300)
encoding/context_encoding/cell_1/fw/basic_lstm_cell/biases:0 (300,)
encoding/context_encoding/cell_1/bw/basic_lstm_cell/weights:0 (225, 300)
encoding/context_encoding/cell_1/bw/basic_lstm_cell/biases:0 (300,)
QP_match/basic_lstm_cell/weights:0 (375, 300)
QP_match/basic_lstm_cell/biases:0 (300,)
Self_match/bidirectional_rnn/fw/basic_lstm_cell/weights:0 (225, 300)
Self_match/bidirectional_rnn/fw/basic_lstm_cell/biases:0 (300,)
Self_match/bidirectional_rnn/bw/basic_lstm_cell/weights:0 (225, 300)
Self_match/bidirectional_rnn/bw/basic_lstm_cell/biases:0 (300,)
basic_lstm_cell/weights:0 (300, 600)
basic_lstm_cell/biases:0 (600,)
177 batches
2018-03-25 17:21:17.286704: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-25 17:21:17.286732: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-25 17:21:17.286748: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-03-25 17:21:17.286755: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-25 17:21:17.286763: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-03-25 17:21:22.248791: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Self_match/bidirectional_rnn/fw/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.249078: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Self_match/bidirectional_rnn/fw/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.249297: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Self_match/bidirectional_rnn/bw/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.249521: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Self_match/bidirectional_rnn/bw/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.249730: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key QP_match/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.249941: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key QP_match/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.251026: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_1/fw/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.251265: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_1/fw/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.251493: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_1/bw/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.251702: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_1/bw/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.251928: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_0/fw/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.252137: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_0/fw/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.252360: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_0/bw/basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.252568: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key encoding/context_encoding/cell_0/bw/basic_lstm_cell/biases not found in checkpoint
2018-03-25 17:21:22.252776: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key basic_lstm_cell/weights not found in checkpoint
2018-03-25 17:21:22.252999: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key basic_lstm_cell/biases not found in checkpoint
Traceback (most recent call last):
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/home/brojo/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key Self_match/bidirectional_rnn/fw/basic_lstm_cell/weights not found in checkpoint
	 [[Node: save/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_9/tensor_names, save/RestoreV2_9/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 105, in <module>
    run()
  File "evaluate.py", line 43, in run
    new_saver.restore(sess, saved_model)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Self_match/bidirectional_rnn/fw/basic_lstm_cell/weights not found in checkpoint
	 [[Node: save/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_9/tensor_names, save/RestoreV2_9/shape_and_slices)]]

Caused by op 'save/RestoreV2_9', defined at:
  File "evaluate.py", line 105, in <module>
    run()
  File "evaluate.py", line 41, in run
    new_saver = tf.train.Saver()
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/brojo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key Self_match/bidirectional_rnn/fw/basic_lstm_cell/weights not found in checkpoint
	 [[Node: save/RestoreV2_9 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_9/tensor_names, save/RestoreV2_9/shape_and_slices)]]

**Comment by unilight** [comment]
Hi @brojokm, can you check your tensorflow version to see if it's 1.2?

**Comment by brojokm** [comment]
Yes, that was the problem.. 
Thank you.

**Comment by unilight** [comment]
You're welcome! Let me know if you have further questions!
